<a href="https://colab.research.google.com/github/RyanHankinsCrenshaw/DTSC4050/blob/main/Week_01-Introduction/Week_01_Coding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 1 - Coding



## Linear Regression Example

In [ ]:
# get the data
# import pandas as pd

# url = 'https://raw.githubusercontent.com/gitmystuff/Datasets/main/Advertising.csv'
# df = pd.read_csv(url, usecols=['TV', 'radio', 'newspaper', 'sales'])
# df.head()

In [ ]:
# df.head(10)

In [ ]:
# df.tail()

In [ ]:
# df.sample(10)

In [ ]:
# df.shape

In [ ]:
# df.info()

In [ ]:
# df.describe()

In [ ]:
# import matplotlib.pyplot as plt

# plt.hist(df['TV']);

In [ ]:
# plt.hist(df['radio'], bins=5)
# plt.xlabel('Amount')
# plt.ylabel('Quantity')
# plt.title('Radio Revenue')
# plt.show();

In [ ]:
# fig, axs = plt.subplots(1, 3, sharey=False, tight_layout=True)
# axs[0].hist(df['TV'])
# axs[0].set_xlabel('TV')

# axs[1].hist(df['radio'])
# axs[1].set_xlabel('radio')

# axs[2].hist(df['newspaper'])
# axs[2].set_xlabel('newspaper')

# plt.show();

In [ ]:
# df.hist()
# plt.tight_layout()

In [ ]:
# import seaborn as sns

# sns.pairplot(df, x_vars=['TV','radio','newspaper'], y_vars='sales',
#              kind='reg',
#              height=5,
#              aspect=0.8,
#              plot_kws={'ci': None, 'line_kws':{'color':'red'}, 'scatter_kws': {'alpha': 0.5}});

In [ ]:
# from sklearn.model_selection import train_test_split

# X_train, X_test, y_train, y_test = train_test_split(df.drop(['sales'], axis=1),
#                                                     df['sales'],
#                                                     test_size=0.20,
#                                                     random_state=42)
# print(X_train.shape)
# print(y_train.shape)

In [ ]:
# from sklearn.linear_model import LinearRegression
# from sklearn.metrics import mean_squared_error, r2_score

# model = LinearRegression()
# model.fit(X_train.values, y_train)
# predictions = model.predict(X_test.values)
# print(f'MSE: {mean_squared_error(y_true=y_test, y_pred=predictions)}')
# print(f'R-Squared: {r2_score(y_test, predictions)}')

In [ ]:
# import numpy as np

# tv = 232.1
# radio = 8.6
# newspaper = 8.7
# model.predict(np.array([tv, radio, newspaper]).reshape(1, -1))

In [ ]:
# list(zip(X_train, model.coef_))

## Python Data Model

https://docs.python.org/3/reference/datamodel.html

In [ ]:
# object
obj = ('abc')
print(id(obj))
print (type(obj))
print(obj)

137550521569520
<class 'str'>
abc


In [ ]:
# type
print(type('abc'))

In [ ]:
# strings (categorical)


In [ ]:
# adding numbers (numerical)
print(1+2)

3


In [ ]:
# adding numbers as strings
print('1'+'2')


12


## Data Structures

https://docs.python.org/3/tutorial/datastructures.html

In [ ]:
# list (mutable)
l = [1, 2.0, 'hello', 3, 'world']
print(l)
l[4] = 'there'
print(l)

[1, 2.0, 'hello', 3, 'world']
[1, 2.0, 'hello', 3, 'there']


In [ ]:
# tuple (immutable)
t = (1, 2,'hello', 3, 'there')
print(t)


In [ ]:
# set
print({1,2,3,3,4,5})

{1, 2, 3, 4, 5}


In [ ]:
# dictionary
d = {'one' : 1, 'two': 2, 'three': 3}

print(d)
print(d['two'])

{'one': 1, 'two': 2, 'three': 3}
2


## Numpy

In [2]:
# random float
# https://www.learndatasci.com/tutorials/applied-introduction-to-numpy-python-tutorial/
import numpy as np

print(np.random.rand())


0.9852096342740946


In [3]:
# random int
import numpy as np

print(np.random.randint(10))

5


In [5]:
# matrix of rows and columns
mat = np.random.randint(10, size=(5, 5))
print(mat)

[[0 2 7 8 3]
 [6 1 6 2 4]
 [9 1 5 1 1]
 [2 9 1 7 5]
 [2 6 4 3 3]]


In [6]:
# slicing [row, col]
print(mat[0:1])

[[0 2 7 8 3]]


In [7]:
# slicing [row start: end, col start: end]
print(mat[0:3, 3:4])

[[8]
 [2]
 [1]]


In [8]:
# slicing [row start: end, col start: end]
print(mat[:3,3:])

[[8 3]
 [2 4]
 [1 1]]


## Pandas

In [9]:
# pandas examples
# https://pandas.pydata.org/docs/user_guide/10min.html
import pandas as pd

print(pd.DataFrame(mat))


   0  1  2  3  4
0  0  2  7  8  3
1  6  1  6  2  4
2  9  1  5  1  1
3  2  9  1  7  5
4  2  6  4  3  3


In [10]:
# assign column names
ex  = pd.DataFrame(mat, columns=['col_one', 'col_two', 'col_three', 'col_four', 'col_five'])
print(ex)

   col_one  col_two  col_three  col_four  col_five
0        0        2          7         8         3
1        6        1          6         2         4
2        9        1          5         1         1
3        2        9          1         7         5
4        2        6          4         3         3


In [11]:
# print col_one
print(ex['col_one'])

0    0
1    6
2    9
3    2
4    2
Name: col_one, dtype: int64


In [12]:
# print using dot notation
print(ex.col_one)

0    0
1    6
2    9
3    2
4    2
Name: col_one, dtype: int64


In [13]:
# print row using loc
print(ex.loc[1])

col_one      6
col_two      1
col_three    6
col_four     2
col_five     4
Name: 1, dtype: int64


In [14]:
# print slice using iloc
print(ex.iloc[0:2,3:5])

   col_four  col_five
0         8         3
1         2         4
